"""Message de migration

Revision ID: 49bfdef45da8
Revises: bb52ec46c5ee
Create Date: 2024-08-30 14:06:08.292183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49bfdef45da8'
down_revision: Union[str, None] = 'bb52ec46c5ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readers', sa.Column('username', sa.String(), nullable=True))
    op.drop_index('ix_readers_email', table_name='readers')
    op.create_index(op.f('ix_readers_username'), 'readers', ['username'], unique=True)
    op.drop_column('readers', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readers', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_readers_username'), table_name='readers')
    op.create_index('ix_readers_email', 'readers', ['email'], unique=1)
    op.drop_column('readers', 'username')
    # ### end Alembic commands ###
